#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

#[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

if [ $hostname = "artixlinux" ] || [ $hostname = "acf" ]; then
	/usr/bin/pipewire &
	/usr/bin/pipewire-pulse &
	/usr/bin/wireplumber &
fi

#systemctl enable netctl-auto@ninanina.service
#ssh-agent dwm > /tmp/dwm.log 2>&1
fcitx5 > /tmp/fcitx5.log 2>&1 &
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm > /tmp/dwm.log 2>&1
